daiquiri/registry/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import authority, availability, capabilities, resource, web

app_name = 'registry'


urlpatterns = [
    path('', TemplateView.as_view(template_name='registry/root.html'), name='root'),
    path('resource', resource, name='resource'),
    path('availability', availability, name='availability'),
    path('capabilities', capabilities, name='capabilities'),
    path('authority/resource', authority, name='authority'),
    path('web/resource', web, name='web'),
]

daiquiri/registry/views.py
from django.http import HttpResponse

from daiquiri.core.renderers.voresource import VoresourceRenderer
from daiquiri.core.renderers.vosi import AvailabilityRenderer, CapabilitiesRenderer

from .vo import get_authority_resource, get_availability, get_capabilities, get_resource, get_web_resource


def resource(request):
    return HttpResponse(VoresourceRenderer().render(get_resource()), content_type='application/xml')


def availability(request):
    return HttpResponse(AvailabilityRenderer().render(get_availability()), content_type='application/xml')


def capabilities(request):
    return HttpResponse(CapabilitiesRenderer().render(get_capabilities()), content_type='application/xml')


def authority(request):
    return HttpResponse(VoresourceRenderer().render(get_authority_resource()), content_type='application/xml')


def web(request):
    return HttpResponse(VoresourceRenderer().render(get_web_resource()), content_type='application/xml')

daiquiri/registry/templates/registry/root.html
{% extends 'core/wide.html' %}
{% load i18n %}

{% block wide %}

    <h1>{% trans 'Registry service' %}</h1>

    <ul>
        <li>
            <a href="{% url 'oai:root' %}">{% trans 'OAI endpoint' %}</a>
        </li>
    </ul>
    <ul>
        <li>
            <a href="{% url 'oai:root' %}?verb=ListIdentifiers&metadataPrefix=ivo_vor">{% trans 'ListIdentifiers' %}</a>
        </li>
        <li>
            <a href="{% url 'oai:root' %}?verb=ListRecords&metadataPrefix=ivo_vor">{% trans 'ListRecords' %}</a>
        </li>
        <li>
            <a href="{% url 'oai:root' %}?verb=ListSets">{% trans 'ListSets' %}</a>
        </li>
    </ul>

    <ul>
        <li>
            <a href="{% url 'registry:resource' %}">{% trans 'VOResource Registry Record' %}</a>
        </li>
        <li>
            <a href="{% url 'registry:availability' %}">{% trans 'VOSI Availability' %}</a>
        </li>
        <li>
            <a href="{% url 'registry:capabilities' %}">{% trans 'VOSI Capabilities' %}</a>
        </li>
    </ul>

    <ul>
        <li>
            <a href="{% url 'registry:authority' %}">{% trans 'VOResource Authority Record' %}</a>
        </li>
        <li>
            <a href="{% url 'registry:web' %}">{% trans 'VOResource Web Record' %}</a>
        </li>
    </ul>

{% endblock %}