daiquiri/datalink/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from daiquiri.jobs.routers import JobRouter

from .views import availability, capabilities, datalink, datalink_semantics
from .viewsets import SyncDatalinkJobViewSet

app_name = 'datalink'

router = JobRouter(trailing_slash=False)
router.register(r'links', SyncDatalinkJobViewSet, basename='link')

urlpatterns = [
    path('', TemplateView.as_view(template_name='datalink/root.html'), name='root'),
    path('semantics', datalink_semantics, name='datalink-semantics'),
    path('<path:ID>/', datalink, name='datalink'),
    path('availability', availability, name='availability'),
    path('capabilities', capabilities, name='capabilities'),

    re_path(r'^', include(router.urls)),
]

daiquiri/datalink/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Datalink(models.Model):

    datalink_id = models.BigAutoField(primary_key=True)
    ID = models.CharField(
        max_length=256,
        db_index=True,
        verbose_name=_('Identifier'),
    )
    access_url = models.CharField(
        max_length=256,
        verbose_name=_('Access URL'),
    )
    service_def = models.CharField(
        max_length=80, blank=True,
        verbose_name=_('Service definition'),
    )
    error_message = models.CharField(
        max_length=256, blank=True,
        verbose_name=_('Error message'),
    )
    description = models.CharField(
        max_length=256, blank=True,
        verbose_name=_('Description'),
    )
    semantics = models.CharField(
        max_length=80, db_index=True, blank=True,
        verbose_name=_('Semantics'),
    )
    content_type = models.CharField(
        max_length=80, db_index=True,
        verbose_name=_('Content type'),
    )
    content_length = models.BigIntegerField(
        null=True,
        verbose_name=_('Content length'),
    )

    class Meta:
        db_table = 'datalink'

    def __str__(self):
        return self.ID

daiquiri/datalink/views.py
from django.http import HttpResponse
from django.shortcuts import render

from daiquiri.core.renderers.vosi import AvailabilityRenderer, CapabilitiesRenderer

from .adapter import DatalinkAdapter
from .settings import DATALINK_CUSTOM_SEMANTICS
from .vo import get_availability, get_capabilities


def datalink(request, ID):
    adapter = DatalinkAdapter()
    context = adapter.get_context_data(request, ID=ID)
    context['custom_semantics'] = DATALINK_CUSTOM_SEMANTICS
    return render(request, 'datalink/datalink.html', context)

def datalink_semantics(request):
    context = { 'custom_semantics': DATALINK_CUSTOM_SEMANTICS }
    return render(request, 'datalink/datalink-semantics.html', context)

def availability(request):
    return HttpResponse(AvailabilityRenderer().render(get_availability()), content_type="application/xml")


def capabilities(request):
    return HttpResponse(CapabilitiesRenderer().render(get_capabilities()), content_type="application/xml")

daiquiri/datalink/templates/datalink/datalink-semantics.html
{% extends 'core/wide.html' %}
{% load i18n %}

{% block wide %}

    <h1>The extension to the Datalink-core dictionary</h1>

    <table class="table table-condensed table-striped">

    <thead>
        <tr>
            <td><b>Term</b></td>
            <td><b>Description</b></td>
        </tr>
    </thead>

    <tbody>

    {% for semantics, description in custom_semantics.items %}
        <tr>
            <td>{{ settings.SITE_URL }}{% url 'datalink:datalink-semantics' %}{{ semantics }}</td>
            <td>{{ description }}</td>
        </tr>
    {% endfor %}

    </tbody>

    </table>
{% endblock %}

daiquiri/datalink/templates/datalink/datalink.html
{% extends 'core/wide.html' %}
{% load i18n %}

<!-- Context

ID

datalinks: (array)
  * ID
  * access_url
  * service_Def
  * error_message
  * description
  * semantics
  * content_type
  * content_length

query_job:
  * jobID
  * schema_name
  * table_name

-->

{% block wide %}

    <h1>{% blocktrans %}Datalinks for {{ ID }}{% endblocktrans %}</h1>

    {% if datalinks %}

        <h2>Data Links</h2>

        <table class="table table-condensed table-striped">

        <thead>
            <tr>
                <!-- <td><b>ID</b></td> -->
                <td><b>access_url</b></td>
                <!-- <td>service_def</td> -->
                <!-- <td>error_message</td> -->
                <td><b>description</b></td>
                <td><b>semantics</b></td>
                <td><b>content_type</b></td>
                <td><b>content_length</b></td>
            </tr>
        </thead>

        <tbody>

        {% for datalink in datalinks %}

            {% if not datalink.service_def %}

            <tr>

                <!-- <td>{{ datalink.ID }}</td> -->
                <td><a href={{ datalink.access_url }}>{{ datalink.access_url }}</a></td>
                <!-- <td>{{ datalink.service_def }}</td> -->
                <!-- <td>{{ datalink.error_message }}</td> -->
                <td>{{ datalink.description }}</td>
                <td>
                    {% if datalink.semantics in custom_semantics %}
                    <a href="{{ settings.SITE_URL }}{% url 'datalink:datalink-semantics' %}{{ datalink.semantics }}">{{ datalink.semantics }}</a>
                    {% else %}
                    <a href="http://www.ivoa.net/rdf/datalink/core{{ datalink.semantics }}">{{ datalink.semantics }}</a>
                    {% endif %}
                </td>
                <td>{{ datalink.content_type }}</td>
                <td>
                    {% if datalink.content_length > 0 %}
                    {{ datalink.content_length | filesizeformat }}
                    {% else %}
                    {{ datalink.content_length }}
                    {% endif %}
                </td>

            </tr>

            {% endif %}

        {% endfor %}

        </tbody>

        </table>

    {% else %}

        <p>No datalinks could be found for this ID.</p>

    {% endif %}

{% endblock %}

daiquiri/datalink/templates/datalink/root.html
{% extends 'core/wide.html' %}
{% load i18n %}

{% block wide %}

    <h1>{% trans 'DATALINK service' %}</h1>

    <ul>
        <li>
            <a href="{% url 'datalink:link-list' %}">{% trans 'links' %}</a>
        </li>
    </ul>
    <ul>
        <li>
            <a href="{% url 'datalink:capabilities' %}">{% trans 'VOSI capabilities' %}</a>
        </li>
        <li>
            <a href="{% url 'datalink:availability' %}">{% trans 'VOSI availability' %}</a>
        </li>
    </ul>

{% endblock %}