daiquiri/tap/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from daiquiri.jobs.routers import JobRouter
from daiquiri.query.viewsets import AsyncQueryJobViewSet, SyncQueryJobViewSet

from .views import availability, capabilities, examples, resource, tables

app_name = 'tap'

router = JobRouter(trailing_slash=False)
router.register(r'sync', SyncQueryJobViewSet, basename='sync')
router.register(r'async', AsyncQueryJobViewSet, basename='async')

urlpatterns = [
    path('', TemplateView.as_view(template_name='tap/root.html'), name='root'),
    path('resource', resource, name='resource'),
    path('availability', availability, name='availability'),
    path('capabilities', capabilities, name='capabilities'),
    path('tables', tables, name='tables'),
    path('examples', examples, name='examples'),

    re_path(r'^', include(router.urls)),
]

daiquiri/tap/models.py
from django.db import models


class Schema(models.Model):

    schema_name = models.CharField(max_length=256)
    utype = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001
    description = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001

    class Meta:
        db_table = 'schemas'

    def __str__(self):
        return self.schema_name


class Table(models.Model):

    schema = models.ForeignKey(Schema, related_name='tables', on_delete=models.CASCADE)

    schema_name = models.CharField(max_length=256)
    table_name = models.CharField(max_length=256)
    table_type = models.CharField(max_length=256)
    utype = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001
    description = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001
    table_index = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'tables'

    def __str__(self):
        return f'{self.schema_name}.{self.table_name}'


class Column(models.Model):

    table = models.ForeignKey(Table, related_name='columns', on_delete=models.CASCADE)

    table_name = models.CharField(max_length=256)
    column_name = models.CharField(max_length=256)
    datatype = models.CharField(max_length=256)
    arraysize = models.IntegerField(null=True, blank=True)
    size = models.IntegerField(null=True, blank=True)
    description = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001
    utype = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001
    unit = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001
    ucd = models.CharField(max_length=256, null=True, blank=True)  # noqa: DJ001
    principal = models.BooleanField(default=False)
    indexed = models.BooleanField(default=False)
    std = models.BooleanField(default=False)
    column_index = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'columns'

    def __str__(self):
        return f'{self.table_name}.{self.column_name}'

daiquiri/tap/views.py
from django.http import HttpResponse
from django.shortcuts import render

from daiquiri.core.renderers.voresource import VoresourceRenderer
from daiquiri.core.renderers.vosi import (
    AvailabilityRenderer,
    CapabilitiesRenderer,
    TablesetRenderer,
)
from daiquiri.query.models import Example

from .vo import get_availability, get_capabilities, get_resource, get_tableset


def resource(request):
    return HttpResponse(VoresourceRenderer().render(get_resource()), content_type='application/xml')


def availability(request):
    return HttpResponse(
        AvailabilityRenderer().render(get_availability()), content_type='application/xml'
    )


def capabilities(request):
    return HttpResponse(
        CapabilitiesRenderer().render(get_capabilities()), content_type='application/xml'
    )


def tables(request):
    return HttpResponse(TablesetRenderer().render(get_tableset()), content_type='application/xml')


def examples(request):
    template = 'tap/examples.html'
    user_agent = request.headers.get('User-Agent', '').lower()
    if 'topcat' in user_agent or 'curl' in user_agent:
        template = 'tap/examples-tap.html'
    return render(
        request, template, {'examples': Example.objects.filter_by_access_level(request.user)}
    )

daiquiri/tap/templates/tap/examples-list.html
{% load i18n %}

<h1>{% trans 'Examples' %}</h1>

<div vocab="http://www.ivoa.net/rdf/examples#">
    {% for example in examples %}
    <div id="example-{{ example.id }}" resource="#example-{{ example.id }}" typeof="example" class="card mb-3">
        <div class="card-header d-flex align-items-center">
            <span property="name">{{ example.name }}</span>
            {% if example.query_language_label %}
            <span class="badge text-bg-secondary ms-auto">{{ example.query_language_label }}</span>
            {% endif %}
        </div>
        <div class="card-body">
            {% if example.description %}
            <p property="description" class="card-text">{{ example.description }}</p>
            {% endif %}
            <pre class="mb-0"><code property="query">{{ example.query_string }}</code></pre>
        </div>
    </div>
    {% endfor %}
</div>

daiquiri/tap/templates/tap/examples-tap.html
{% load static %}<!DOCTYPE html>
<html>

{% block htmlargs %}version="XHTML+RDFa 1.1" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"{% endblock %}

{% block bodyargs %}vocab="ivo://ivoa.net/std/DALI-examples"{% endblock %}

<head>


{% include 'core/base_head.html' %}

</head>

<body>

<div class="content">
  {% include 'tap/examples-list.html' %}
</div>

</body>

</html>

daiquiri/tap/templates/tap/examples.html
{% extends 'core/wide.html' %}
{% load static %}
{% load i18n %}

{% block wide %}

    {% include 'tap/examples-list.html' %}

{% endblock %}

daiquiri/tap/templates/tap/root.html
{% extends 'core/wide.html' %}
{% load i18n %}

{% block wide %}

    <h1>{% trans 'TAP service' %}</h1>

    <ul>
        <li>
            <a href="{% url 'tap:sync-list' %}">{% trans 'sync' %}</a>
        </li>
        <li>
            <a href="{% url 'tap:async-list' %}">{% trans 'async' %}</a>
        </li>
    </ul>
    <ul>
        <li>
            <a href="{% url 'tap:resource' %}">{% trans 'VOResource Record' %}</a>
        </li>
        <li>
            <a href="{% url 'tap:capabilities' %}">{% trans 'VOSI capabilities' %}</a>
        </li>
        <li>
            <a href="{% url 'tap:tables' %}">{% trans 'VOSI tableset' %}</a>
        </li>
    </ul>
    <ul>
        <li>
            <a href="{% url 'tap:examples' %}">{% trans 'examples' %}</a>
        </li>
    </ul>

{% endblock %}