daiquiri/conesearch/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from .views import availability, capabilities, resource
from .viewsets import ConeSearchView

app_name = 'conesearch'

urlpatterns = [
    path('', TemplateView.as_view(template_name='conesearch/root.html'), name='root'),
    path('resource', resource, name='resource'),
    path('availability', availability, name='availability'),
    path('capabilities', capabilities, name='capabilities'),
    re_path(r'^api/(?P<resource>.+)/$', ConeSearchView.as_view(), name='search'),
]

daiquiri/conesearch/views.py
from django.http import HttpResponse

from daiquiri.core.renderers.voresource import VoresourceRenderer
from daiquiri.core.renderers.vosi import AvailabilityRenderer, CapabilitiesRenderer

from .vo import get_availability, get_capabilities, get_resource


def resource(request):
    return HttpResponse(VoresourceRenderer().render(get_resource()), content_type="application/xml")


def availability(request):
    return HttpResponse(AvailabilityRenderer().render(get_availability()), content_type="application/xml")


def capabilities(request):
    return HttpResponse(CapabilitiesRenderer().render(get_capabilities()), content_type="application/xml")

daiquiri/conesearch/templates/conesearch/root.html
{% extends 'core/wide.html' %}
{% load i18n %}

{% block wide %}

    <h1>{% trans 'Cone Search service' %}</h1>

    <ul>
        <li>
            <a href="{% url 'conesearch:resource' %}">{% trans 'VOResource Record' %}</a>
        </li>
        <li>
            <a href="{% url 'conesearch:availability' %}">{% trans 'VOSI availability' %}</a>
        </li>
        <li>
            <a href="{% url 'conesearch:capabilities' %}">{% trans 'VOSI capabilities' %}</a>
        </li>
    </ul>

{% endblock %}